import {authorized,denied} from '@/lib/access';
import {englishLabel} from "@/lib/english";
import {store,sameOrigin,insertCollectedEntries} from '@/lib/store';
import {normalize} from '@/lib/signal';
export async function GET(){if(!await authorized())return denied();try{const r=await store().prepare('SELECT payload FROM entries ORDER BY created_at DESC LIMIT 2000').all<{payload:string}>();return Response.json({entries:r.results.map(x=>{const e=JSON.parse(x.payload);e.source=englishLabel(e.source);if(e.analysis){for(const k of ["engine","action","topic"])e.analysis[k]=englishLabel(e.analysis[k]);}return e;})},{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'Could not load materials. Please retry.'},{status:503});}}
export async function POST(req:Request){if(!await authorized())return denied();try{sameOrigin(req);const body:any=await req.json();if(!Array.isArray(body.entries)||!body.entries.length||body.entries.length>200)throw new Error('Import 1–200 materials at a time');const entries=body.entries.map(normalize);const rows=await Promise.all(entries.map(async(e:any)=>{const u=e.url.match(/(?:x|twitter)\.com\/[^/]+\/status\/(\d+)/);const fp=u?'x:'+u[1]:Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(e.text.trim())))).map(n=>n.toString(16).padStart(2,'0')).join('');return {id:e.id,fingerprint:fp,payload:JSON.stringify(e),created_at:e.createdAt};}));const result=await insertCollectedEntries(rows);if(!result.allowed)return Response.json({error:'Collector holds up to 100 posts. Export and delete posts to make room. Nothing was imported.',code:'COLLECTION_FULL'},{status:409});return Response.json({added:result.added,total:entries.length});}catch(e){return Response.json({error:e instanceof Error?e.message:'Save failed. Your input has been kept.'},{status:400});}}
export async function PATCH(req:Request){if(!await authorized())return denied();try{sameOrigin(req);const b:any=await req.json();if(typeof b.id!=='string')throw new Error('Material is missing');const r=await store().prepare('SELECT payload FROM entries WHERE id=?').bind(b.id).first<{payload:string}>();if(!r)return Response.json({error:'Material not found'},{status:404});const e=JSON.parse(r.payload);if(b.status!==undefined){if(!['inbox','planned','later','done','archived'].includes(b.status))throw new Error('Invalid status');e.status=b.status;}if(typeof b.draft==='string')e.draft=b.draft.slice(0,16000);if(typeof b.feedback==='string')e.feedback=b.feedback.slice(0,500);await store().prepare('UPDATE entries SET payload=? WHERE id=?').bind(JSON.stringify(e),e.id).run();return Response.json({entry:e});}catch{return Response.json({error:'Update failed. Please retry.'},{status:400});}}

export async function DELETE(req:Request){if(!await authorized())return denied();try{sameOrigin(req);const b:any=await req.json();if(typeof b.id!=='string'||!b.id.trim()||b.id.length>200)return Response.json({error:'A valid material ID is required'},{status:400});await store().prepare('DELETE FROM entries WHERE id=?').bind(b.id).run();return Response.json({deleted:true,id:b.id});}catch{return Response.json({error:'Deletion failed. Please retry.'},{status:400});}}

